openapi: 3.0.0
info:
  version: 1.0.0
  title: Realmeet
servers:
  - url: 'http://localhost:3000'
tags:
  - name: room
    description: Everything to you manager your room
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /rooms/{id}:
    get:
      summary: 'Return a room by ID'
      operationId: getRoom
      tags:
        - room
      parameters:
        - name: id
          in: path
          description: ID of the room
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
components:
  schemas:
    RoomDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        seats:
          type: integer
    ResponseError:
      type: object
      required:
        - code
        - status
        - message
      properties:
        code:
          type: integer
          format: int32
        status:
          type: string
        message:
          type: string
  securitySchemes:
    room_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://realmeet.swagger.io/oauth/authorize
          scopes:
            write:rooms: modify rooms in your account
            read:rooms: read your rooms
    api_key:
      type: apiKey
      name: api_key
      in: header